/var/log/madina-express/*.log /var/lib/madina-express/.pm2/pm2.log {
    daily
    maxsize 10M
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su madina-express madina-express
}
